[package]
name = "compiler"
version = "0.1.0"
authors = ["Varun Potti <potti.varun07@gmail.com>", "Carter Snook <cartersnook04@gmail.com"]
edition = "2018"

[dependencies]
lexer = { path = "../lexer" }
codegen = "0.1.3"