[package]
name = "compiler"
version = "0.1.0"
authors = ["VarunPotti <potti.varun07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

llvm-sys = "120"
torq-llvm = {path = "../torq-llvm"}